### ISSUE TITLE
are “root” and “file” really necessary?

### ISSUE THREAD

**Issue by zamfofex** [alwinb/url-specification#1]
Hello! First of all, I wanted to be able to thank you for putting work on this! I have recently finished reading your specification, and in my personal opinion, it is much easier to read and follow than the WHATWG one! :tada:

I have noticed you have inherited the concept of “root” and “file” from your `reurl` library, but I have always kinda wondered whether that is the best approach to model paths. Wouldn’t it make more sense to have a single sequence of “parts”, each prefixed by a slash when printing?

Then, the grammar could be rewritten to:

> ~~~
> auth-path ::= auth-drive [ s path ] — in file-mode
> auth-path ::= s s authority [ s path ] — otherwise
> path ::= (part s)* part
> part ::= pchar*
> ~~~

The only “quirk” I can see arriving would be regarding the `upto` operation, which would have to take a second URL, as opposed to a plain `order`:

> `(url1 upto url2)` is defined to be the shortest prefix of `url1` that contains all tokens of `url1` with a type strictly smaller than `(ord url2)` followed by either:
>
> - `ε` if the type of the first token of `url2` is not `part`, or
> - `ε` if the first token of `url2` is `(part ε)`, or
> - all except the last `part` token of `url1` if there is at least one such token in `url1`, or
> - `ε` otherwise.

If that’s too inelegant, maybe at least `file` could be removed, keeping only `part` and `root`.

**Comment by alwinb** [comment]
Thank you! I appreciate the support, and I appreciate that you haven taken the time to read it and understand it! 

Yes, this way of modelling the path does seem a bit strange, doesn't it? I tried alternatives though, but each time I ended up deciding that the current solution made the better trade-offs. It is probably a good idea to add a few lines that explains why the path is modelled in [the current] way in any case. 

I may need a bit more time to study your proposal, but am I correct that you mean to model e.g. 
- `foo/bar` as (**part** foo) • (**part** bar)
- `/foo/bar` as (**part** ε) • (**part** foo) • (**part** bar)
- `/foo/bar/` as (**part** ε) • (**part** foo) • (**part** bar) • (**part** ε)  ?

I may have another look at it, but I must add that my priority for this project at the moment is to fill in the gaps that remain in the specification and then to identify the exact differences with the RFC. In the hope to resolve the differences. Enough things to do :)

**Comment by zamfofex** [comment]
> but am I correct that you mean to model e.g. […]

Yes, but I was imagining that’d be the case only for relative path URLs. In absolute URLs, where there can’t be a relative path, you wouldn’t have the leading `(part ε)`.

> Enough things to do

Yeah, fair enough! :+1: It goes without saying, but feel free to take your time! Thank you for the attention anyway!

**Comment by zamfofex** [comment]
I wanted to mention: On retrospect, I think `root` (or, rather, now `path-root`) works well as is, and although I really wanted for `dir` and `file` to be able to be collapsed, I don’t think that’s actually simpler, because of how an empty `""` URL resolves differently compared to `"."` for example.

~~~
"" against "xx://example.com/txt/hello.txt" = "xx://example.com/txt/hello.txt"
"." against "xx://example.com/txt/hello.txt" = "xx://example.com/txt/"
"test.txt" against "xx://example.com/txt/hello.txt" = "xx://example.com/txt/test.txt"
~~~

I’d expect for them to behave similarly, and if they did, it would make handling this case using just `part` easier, but since they don’t, I am unsure whether that would actually make more sense.

If you think there is merit to the idea of simplifying some of these constructs, though, please feel free to reopen this issue!

**Comment by alwinb** [comment]
Well, I agree that on first, and second sight, the current way of modelling the path is not so intuitive. Especially, in actual implementations, where it makes sense to collect the **dir** tokens into an array, thus parsing e.g. `//host/foo1/foo2/bar` as follows. 

```
{ 
  host: 'host',
  root: '/',
  dirs: ['foo1', 'foo2'],
  file: 'bar'
}
```

But it is quite natural if you consider resolution and normalisation. So I'm reasonably content with this design, while I remain open to new ideas. 

One could of course collect root, dirs and file into a 'path' object, and / or replace the path-root with a boolean or model it by adding distinct AbsolutePath and a RelativePath classes. And / or the path-root can be dropped completely from an (absolute-) URL class. But for the spec and reference implementation I think the current solution is ok. 

Anyway, thanks for taking an interest and for having a look at this!
